adjusted actions file

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -1,35 +1,53 @@
-name: Build and Deploy
+name: Deploy to GitHub Pages
 on:
   push:
     branches:
-      - master
+      - main
+  workflow_dispatch:
 permissions:
+  contents: read
   pages: write
   id-token: write
+concurrency:
+  group: "pages"
+  cancel-in-progress: false
 jobs:
   build:
-    # Recommended if you intend to make multiple deployments in quick succession.
-    concurrency: ci-${{ github.ref }}
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout 🛎️
+      - name: Checkout Repository
         uses: actions/checkout@v4
-        # This example project is built using npm and outputs the result to the 'build' folder.
-        # Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
-      
-      - name: Install and Build 🔧
+      - name: Detect package manager
+        id: detect-package-manager
         run: |
-          npm ci
-          npm run build
-      
-      - name: Test 🧪
-        run: npm run test
-      
-      - name: Setup Pages 🔧📄
-        id: pages
-        uses: actions/configure-pages@v4
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "14"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build project
+        run: ${{ steps.detect-package-manager.outputs.runner }} npm run build
       - name: Upload artifact
-        uses: actions/upload-pages-artifact@v3
+        uses: actions/upload-pages-artifact@v2
+        with:
+          path: ./build
+  # Deployment job
   deploy:
     environment:
       name: github-pages
@@ -37,9 +55,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-      - name: Deploy to Github Pages 🚀
+      - name: Deploy to GitHub Pages
         id: deployment
-        uses: actions/deploy-pages@v4
-        # uses: JamesIves/github-pages-deploy-action@v4
-        # with:
-        #   folder: build # The folder the action should deploy.
+        uses: actions/deploy-pages@v3
